version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - java -version
      - mvn install
      - aws cloudformation package --template-file template.yml --s3-bucket manthan-bucket555 --output-template-file template-output.yml --debug
  post_build:
    commands:
      - echo Build completed on `date`
      
cache:
  paths:
    - '/root/.m2/**/*'

artifacts:
  files:
    - target/lambdaTrigger.jar
    - template-output.yml